import { firebaseConfig } from './firebase-config.js';
import { initializeApp, getApps } from 'https://www.gstatic.com/firebasejs/10.12.5/firebase-app.js';
import { getAuth, onAuthStateChanged } from 'https://www.gstatic.com/firebasejs/10.12.5/firebase-auth.js';
import { collection, doc, getDoc, getFirestore, limit, onSnapshot, query, runTransaction, serverTimestamp, setDoc, where } from 'https://www.gstatic.com/firebasejs/10.12.5/firebase-firestore.js';

const app = getApps().length ? getApps()[0] : initializeApp(firebaseConfig);
const auth = getAuth(app);
const db = getFirestore(app);
const $ = (s) => document.querySelector(s);
const state = { user:null, profile:null, online:false, available:[], visible:null, active:null, unsubAvailable:null, unsubActive:null };

function toast(message,error=false){const el=$('#toast');if(!el)return;el.textContent=message;el.className=`toast show${error?' error':''}`;clearTimeout(toast.t);toast.t=setTimeout(()=>el.className='toast',2600)}
function number(v,f=0){const n=Number(v);return Number.isFinite(n)?n:f}
function km(a,b){if(!a||!b)return Infinity;const lat1=number(a.latitude??a.lat,NaN),lon1=number(a.longitude??a.lng,NaN),lat2=number(b.latitude??b.lat,NaN),lon2=number(b.longitude??b.lng,NaN);if(![lat1,lon1,lat2,lon2].every(Number.isFinite))return Infinity;const r=x=>x*Math.PI/180,dLat=r(lat2-lat1),dLon=r(lon2-lon1);const x=Math.sin(dLat/2)**2+Math.cos(r(lat1))*Math.cos(r(lat2))*Math.sin(dLon/2)**2;return 6371*2*Math.atan2(Math.sqrt(x),Math.sqrt(1-x))}
function normalize(s){const d=s.data(),pickup=d.pickup||{},drop=d.drop||{},distance=km(state.profile?.location,pickup.location||d.pickupLocation);return{firestoreId:s.id,id:d.orderNumber||s.id,status:d.status,pickup:pickup.name||d.pickupName||d.storeName||'Pickup store',pickupAddress:pickup.address||d.pickupAddress||'',pickupLocation:pickup.location||d.pickupLocation,pickupDistance:Number.isFinite(distance)?`${distance.toFixed(1)} km away`:'Nearby',drop:drop.name||d.customerName||'Customer',dropAddress:drop.address||d.dropAddress||'',dropLocation:drop.location||d.dropLocation,distance:d.distanceText||'Distance pending',duration:d.durationText||'20–30 min',items:`${number(d.itemCount,Array.isArray(d.items)?d.items.length:1)} items`,payment:d.paymentMode||'Cash on Delivery',payout:number(d.riderPayout??d.payout,0),customerPhone:d.customerPhone||'',raw:d,kmToPickup:distance}}
function setOnlineUi(online){state.online=online;const t=$('#online-toggle');if(t)t.checked=online;const badge=$('#availability-badge'),title=$('#availability-title'),text=$('#availability-text');if(badge){badge.textContent=online?'Online':'Offline';badge.className=`availability-badge ${online?'online':'offline'}`}if(title)title.textContent=online?'You are online':'You are offline';if(text)text.textContent=online?'Merchant-ready orders will appear automatically.':'Go online to receive nearby delivery requests.';$('#offline-state')?.classList.toggle('hidden',online||!!state.active);$('#searching-state')?.classList.toggle('hidden',!online||!!state.visible||!!state.active);if(!online)$('#order-request')?.classList.add('hidden')}
async function savePresence(){if(!state.user)return;await setDoc(doc(db,'riders',state.user.uid),{isOnline:state.online,status:state.online?'online':'offline',location:state.profile?.location||null,lastSeenAt:serverTimestamp()},{merge:true})}
function fillRequest(o){state.visible=o;$('#order-id').textContent=`#${o.id}`;$('#order-payout').textContent=`₹${o.payout}`;$('#pickup-store').textContent=o.pickup;$('#pickup-distance').textContent=o.pickupDistance;$('#drop-area').textContent=o.dropAddress;$('#order-distance').textContent=o.distance;$('#order-time').textContent=o.duration;$('#order-items').textContent=o.items;$('#payment-mode').textContent=o.payment;$('#searching-state')?.classList.add('hidden');$('#order-request')?.classList.remove('hidden');$('#request-count').textContent=`${state.available.length} available`}
function nextRequest(){if(!state.online||state.active)return;const next=state.available.find(o=>o.firestoreId!==state.visible?.firestoreId)||state.available[0];if(next)fillRequest(next);else{state.visible=null;$('#order-request')?.classList.add('hidden');$('#searching-state')?.classList.remove('hidden');$('#request-count').textContent='0 available'}}
function listenAvailable(){state.unsubAvailable?.();state.unsubAvailable=onSnapshot(query(collection(db,'orders'),where('status','==','ready_for_pickup'),limit(25)),snap=>{state.available=snap.docs.map(normalize).filter(o=>!Number.isFinite(o.kmToPickup)||o.kmToPickup<=8).sort((a,b)=>a.kmToPickup-b.kmToPickup);if(state.visible&&!state.available.some(o=>o.firestoreId===state.visible.firestoreId))state.visible=null;nextRequest()},e=>{console.error(e);toast('Orders load nahi hue. Firestore rules/index check karo.',true)})}
function renderActive(){const o=state.active;if(!o)return;$('#active-order-card')?.classList.remove('hidden');$('#active-order-id').textContent=`Order #${o.id}`;const s=o.status;if(s==='accepted'){ $('#active-step-label').textContent='TO PICKUP';$('#active-progress').style.width='25%';$('#active-destination-type').textContent='Pickup from';$('#active-destination-name').textContent=o.pickup;$('#active-destination-address').textContent=o.pickupAddress;$('#advance-order-btn').textContent='I have arrived'}else if(s==='arrived_pickup'){ $('#active-step-label').textContent='AT STORE';$('#active-progress').style.width='50%';$('#active-destination-type').textContent='Pickup from';$('#active-destination-name').textContent=o.pickup;$('#active-destination-address').textContent=o.pickupAddress;$('#advance-order-btn').textContent='Order picked up'}else if(s==='picked_up'){ $('#active-step-label').textContent='TO CUSTOMER';$('#active-progress').style.width='75%';$('#active-destination-type').textContent='Deliver to';$('#active-destination-name').textContent=o.drop;$('#active-destination-address').textContent=o.dropAddress;$('#advance-order-btn').textContent='Complete delivery'} }
function listenActive(id){state.unsubActive?.();state.unsubActive=onSnapshot(doc(db,'orders',id),snap=>{if(!snap.exists()){state.active=null;$('#active-order-card')?.classList.add('hidden');return}const o=normalize(snap);if(o.raw.assignedRiderId!==state.user?.uid||!['accepted','arrived_pickup','picked_up'].includes(o.status)){state.active=null;$('#active-order-card')?.classList.add('hidden');nextRequest();return}state.active=o;renderActive()})}
async function recoverActive(){const q=query(collection(db,'orders'),where('assignedRiderId','==',state.user.uid),limit(10));const unsub=onSnapshot(q,s=>{const found=s.docs.map(normalize).find(o=>['accepted','arrived_pickup','picked_up'].includes(o.status));if(found&&!state.active){state.active=found;listenActive(found.firestoreId);renderActive()}unsub()})}
async function accept(){const o=state.visible;if(!o||!state.user||state.active)return;const b=$('#accept-order-btn');b.disabled=true;b.textContent='Accepting…';try{const ref=doc(db,'orders',o.firestoreId);await runTransaction(db,async tx=>{const s=await tx.get(ref);if(!s.exists())throw new Error('NOT_FOUND');const d=s.data();if(d.status!=='ready_for_pickup'||d.assignedRiderId)throw new Error('TAKEN');tx.update(ref,{status:'accepted',assignedRiderId:state.user.uid,assignedRiderName:state.profile?.fullName||state.user.displayName||'Rider',riderAcceptedAt:serverTimestamp(),acceptedAt:serverTimestamp(),updatedAt:serverTimestamp()})});state.active={...o,status:'accepted'};state.visible=null;$('#order-request')?.classList.add('hidden');listenActive(o.firestoreId);renderActive();toast('Order accepted.')}catch(e){toast(e.message==='TAKEN'?'Ye order kisi aur rider ne accept kar liya.':'Order accept nahi hua.',true);nextRequest()}finally{b.disabled=false;b.textContent='Accept order'}}
async function advance(){const o=state.active;if(!o)return;const next={accepted:'arrived_pickup',arrived_pickup:'picked_up',picked_up:'completed'}[o.status];if(!next)return;const b=$('#advance-order-btn');b.disabled=true;try{const ref=doc(db,'orders',o.firestoreId);await runTransaction(db,async tx=>{const s=await tx.get(ref);if(!s.exists())throw new Error('NOT_FOUND');const d=s.data();if(d.assignedRiderId!==state.user.uid||d.status!==o.status)throw new Error('INVALID');const patch={status:next,updatedAt:serverTimestamp()};if(next==='arrived_pickup')patch.arrivedPickupAt=serverTimestamp();if(next==='picked_up')patch.pickedUpAt=serverTimestamp();if(next==='completed')patch.completedAt=serverTimestamp();tx.update(ref,patch)});if(next==='completed'){state.active=null;$('#active-order-card')?.classList.add('hidden');toast('Delivery completed.');nextRequest()}}catch(e){console.error(e);toast('Order update failed.',true)}finally{b.disabled=false}}
function openNavigation(){const o=state.active;if(!o)return;const target=o.status==='picked_up'?o.dropLocation:o.pickupLocation;if(!target)return toast('Location unavailable.',true);window.open(`https://www.google.com/maps/dir/?api=1&destination=${target.latitude},${target.longitude}`,'_blank')}

$('#online-toggle')?.addEventListener('change',async e=>{setOnlineUi(e.target.checked);try{await savePresence();if(state.online)nextRequest()}catch{toast('Online status save nahi hua.',true)}});
$('#accept-order-btn')?.addEventListener('click',accept);
$('#reject-order-btn')?.addEventListener('click',()=>{state.visible=null;nextRequest()});
$('#advance-order-btn')?.addEventListener('click',advance);
$('#open-navigation-btn')?.addEventListener('click',openNavigation);
$('#call-action-btn')?.addEventListener('click',()=>{if(state.active?.customerPhone)location.href=`tel:${String(state.active.customerPhone).replace(/[^+\d]/g,'')}`;else toast('Customer phone unavailable.',true)});

onAuthStateChanged(auth,async user=>{state.user=user;state.unsubAvailable?.();state.unsubActive?.();state.available=[];state.visible=null;state.active=null;if(!user)return;const snap=await getDoc(doc(db,'riders',user.uid));state.profile=snap.exists()?snap.data():null;if(!state.profile?.onboardingComplete)return;setOnlineUi(Boolean(state.profile.isOnline));listenAvailable();recoverActive()});
